import './globals.css'
import { Lato } from 'next/font/google'

const lato = Lato({ subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-lato'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html className='bg-white' lang="en">
      <body className={lato.className}>{children}</body>
    </html>
  )
}
